### ISSUE TITLE
Build ROS driver for GPS

### ISSUE THREAD

**Issue by krush11** [DTUSDC/ros#10]
The GPS used is [AtlasLink GNSS](https://www.navtechgps.com/atlaslink_gnss_smart_antenna/).
 
## To Do:
- Build a encoder to read data from GPS
- publish relevant output to a ROS topic

**Comment by krush3r** [comment]
Key features of [AtlasLink GNSS](https://www.hemispheregnss.com/wp-content/uploads/2019/12/hemispheregnss_atlaslink_datasheet_web.pdf) :
-   Atlas® L-band corrections
-   Athena™ RTK engine
- Powerful WebUI accessed via Wi-Fi
- Internal memory for data logging, download, and upload
- Environment-proven enclosure for the most aggressive user scenarios
