### ISSUE TITLE
Build Motor Driver

### ISSUE THREAD

**Issue by obviyus** [DTUSDC/ros#11]
Build ROS motor driver for [Cytron SmartDrive Duo 30](https://www.cytron.io/p-30amp-7v-35v-smartdrive-dc-motor-driver-2-channels).

**Comment by krush3r** [comment]
**TO DO:** 
1. Develop python script to publish the following topics:
  - vel
2. Build a plugin to access two motor drivers

**Comment by krush3r** [comment]
Motor driver built and running successfully.
