### ISSUE TITLE
Build maze world for NavStack testing

### ISSUE THREAD

**Issue by obviyus** [DTUSDC/ros#13]
A maze world would help with extended NavStack testing. It should be stored in the repo and called when `nvigation.launch` is started. Here's a possible resource:
- [Creating a ROS Gazebo maze simulation for Turtlebot3](https://asankagp.github.io/turtlebotprojects/tutorials/Tutorial%205%20Creating%20a%20ROS%20Gazebo%20maze%20simulation%20for%20Turtlebot3.pdf)

**Comment by tanmayj2020** [comment]
Implemented on same day
