### ISSUE TITLE
NavStack Implementation

### ISSUE THREAD

**Issue by tanmayj2020** [DTUSDC/ros#6]
Following packages have to understood properly for implementing navigation stack in ROS-
- global-planner
- local-planner
- rotate-recovery
- clear-costmap-recovery
- costmap 2d
- map-server
- AMCl
- Gmapping

**Comment by tanmayj2020** [comment]
NavStack has been implemented still working on fine tuning the parameters.

**Comment by obviyus** [comment]
Using the following document as reference for fine tuning ROS parameters:

- http://kaiyuzheng.me/documents/navguide.pdf

**Comment by obviyus** [comment]
Continued in #12.
