### ISSUE TITLE
Build ROS driver for IMU

### ISSUE THREAD

**Issue by krush3r** [DTUSDC/ros#9]
The IMU used is Sparton [AHRS-8P](https://www.spartonnavex.com/product/ahrs-8p/). 

## Todo:
- build a encoder to read data from IMU
- publish relevant output to a ROS topic

**Comment by obviyus** [comment]
Study the following standards before implementing:
- [REP 103](https://www.ros.org/reps/rep-0103.html)
- [REP 105](https://www.ros.org/reps/rep-0105.html)

**Comment by krush3r** [comment]
Driver for IMU (Sparton ahrs-8p) ready and now publishes:-
- Orientation
- angular velocity
- linear acceleration

Using code base from: https://github.com/RoboticsClubatUCF/ucf_AHRS

**Comment by krush3r** [comment]
Improved output data format which now publishes
- Orientation in degrees
- Angular velocity in radian/sec
- linear acceleration in m/s^2

**Comment by krush3r** [comment]
IMU driver made according to the standards of
- [REP 103](https://www.ros.org/reps/rep-0103.html)
- [REP 105](https://www.ros.org/reps/rep-0105.html)
